name: pizzaprint_v4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  geolocator: ^13.0.3
  flutter_dotenv: ^5.2.1
  permission_handler: ^11.4.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  mapbox_maps_flutter: ^2.7.0
  shared_preferences: ^2.5.2
  dio: ^4.0.0
  intl: ^0.17.0
  convex_bottom_bar: ^3.2.0
  cached_network_image: ^3.4.1
  image: ^4.5.4
  socket_io_client: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/