// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXWSYCH2VrnZGGSerxBoY52L3cmZZzvwc',
    appId: '1:412279854118:web:34c54553c2ae0e402202e7',
    messagingSenderId: '412279854118',
    projectId: 'pizzasprintnotification',
    authDomain: 'pizzasprintnotification.firebaseapp.com',
    storageBucket: 'pizzasprintnotification.firebasestorage.app',
    measurementId: 'G-TJNKLLFJ04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbctx-1rArQxLRxih2oZgnC_5v0wdPhqQ',
    appId: '1:412279854118:android:9eb77c6d370f12652202e7',
    messagingSenderId: '412279854118',
    projectId: 'pizzasprintnotification',
    storageBucket: 'pizzasprintnotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30wjVGmPs3zTaBoLxO28HdLjoNnkn3NU',
    appId: '1:412279854118:ios:d432a4e8430ee1f92202e7',
    messagingSenderId: '412279854118',
    projectId: 'pizzasprintnotification',
    storageBucket: 'pizzasprintnotification.firebasestorage.app',
    androidClientId: '412279854118-3ser5g00k8tm6s0jrb7aglraafgpveqk.apps.googleusercontent.com',
    iosClientId: '412279854118-ri5jolsl9qa6hasu0rb559gtfgpn9jbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaprintV4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30wjVGmPs3zTaBoLxO28HdLjoNnkn3NU',
    appId: '1:412279854118:ios:d432a4e8430ee1f92202e7',
    messagingSenderId: '412279854118',
    projectId: 'pizzasprintnotification',
    storageBucket: 'pizzasprintnotification.firebasestorage.app',
    androidClientId: '412279854118-3ser5g00k8tm6s0jrb7aglraafgpveqk.apps.googleusercontent.com',
    iosClientId: '412279854118-ri5jolsl9qa6hasu0rb559gtfgpn9jbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaprintV4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXWSYCH2VrnZGGSerxBoY52L3cmZZzvwc',
    appId: '1:412279854118:web:a2598b2061069fcd2202e7',
    messagingSenderId: '412279854118',
    projectId: 'pizzasprintnotification',
    authDomain: 'pizzasprintnotification.firebaseapp.com',
    storageBucket: 'pizzasprintnotification.firebasestorage.app',
    measurementId: 'G-2NE96Y2NQ8',
  );
}
